Enhance build workflow with Linux support

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -106,20 +106,63 @@ jobs:
             HobbySpark-${{ steps.version.outputs.version }}-WindowsSetup.exe
             HobbySpark-${{ steps.version.outputs.version }}-Windows-Portable-No-Save.zip
             
-            
-
-          
-        
-      
-        
-        
-        
-  second-one:
+  ubuntu-build:
     runs-on: ubuntu-latest
+    needs: build
+    defaults:
+      run:
+        shell: bash
+
     steps:
       - uses: actions/checkout@v4
-      - name: startoff
-        run: echo "SECOND JOB"
+      - name: Adding python
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.13
+
+      - name: Installing packages
+        run: | 
+          python -m pip install --upgrade pip
+          python -m pip install -r requirements.txt
+          python -m pip install pyinstaller
+
+      - name: Determine Version
+        id: version
+        shell: pwsh
+        run: |
+            $v = "${{ github.ref_name }}"
+            $v = $v.TrimStart("v")
+            "version=$v" >> $env:GITHUB_OUTPUT
+
+      - name: Compile excecutable
+        run: pyinstaller tks.spec
+
+      - name: Verify that excecutable exists
+        run: |
+          if not exist dist\HobbySpark\HobbySpark.exe (
+              echo "ERROR:"
+              echo "Pyinstaller failed"
+              exit /b 1
+          )
+
+      - name: Compress
+        run: tar -czf HobbySpark-${VERSION}-Linux-Portable.tar.gz dist/HobbySpark
+
+      - name: Verify Debian package
+        shell: bash
+        run: |
+          if [ ! -f HobbySpark-${{ steps.version.outputs.version }}-amd64.deb ]; then
+            echo "Debian package was not generated."
+            exit 1
+          fi
+      - name: Upload Debian package
+        uses: actions/upload-artifact@v4
+        with:
+          name: Linux-Debian
+          path: |
+              HobbySpark-${{ steps.version.outputs.version }}-amd64.deb
+              HobbySpark-${{ steps.version.outputs.version }}-Linux-Portable.tar.gz
+    
         
         
       
