Refactor GitHub Actions workflow for HobbySpark

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,13 +31,14 @@ jobs:
       - name: Compile excecutable
         run: pyinstaller tks.spec
 
-      - name: Verify that excecutable exists
+      - name: Verify executable exists
+        shell: bash
         run: |
-          if not exist dist\HobbySpark\HobbySpark.exe (
-              echo "ERROR:"
-              echo "Pyinstaller failed"
-              exit /b 1
-          )
+          if [ ! -f "dist/HobbySpark/HobbySpark" ]; then
+            echo "ERROR:"
+            echo "PyInstaller failed"
+            exit 1
+          fi
       - name: Install InnoSetup
         shell: powershell
         run: choco install innosetup -y
